# Generated by Django 6.0.5 on 2026-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xbinning', models.IntegerField()),
                ('ybinning', models.IntegerField()),
                ('creator', models.CharField(max_length=16)),
                ('telescop', models.CharField(max_length=16)),
                ('exposure', models.FloatField()),
                ('aexptime', models.FloatField()),
                ('rexptime', models.FloatField()),
                ('date_obs', models.DateTimeField()),
                ('time_obs', models.DateTimeField()),
                ('cmdra', models.CharField(max_length=32)),
                ('cmddec', models.CharField(max_length=32)),
                ('cmdrol', models.FloatField()),
                ('cmdq0', models.FloatField()),
                ('cmdq1', models.FloatField()),
                ('cmdq2', models.FloatField()),
                ('cmdq3', models.FloatField()),
                ('ra', models.CharField(max_length=32)),
                ('dec', models.CharField(max_length=32)),
                ('objctra', models.CharField(max_length=32)),
                ('objctdec', models.CharField(max_length=32)),
                ('objctrol', models.FloatField()),
                ('ela_min', models.FloatField()),
                ('ela_max', models.FloatField()),
                ('ela_ang', models.FloatField()),
                ('sun_min', models.FloatField()),
                ('sun_max', models.FloatField()),
                ('temp_ccd', models.FloatField()),
                ('object', models.CharField(max_length=32)),
                ('observer', models.CharField(max_length=8)),
                ('intent', models.CharField(max_length=16)),
                ('instrume', models.CharField(max_length=16)),
                ('targtype', models.CharField(max_length=8)),
                ('prop_id', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('moving', models.CharField(max_length=4)),
                ('geo_lat', models.CharField(max_length=16)),
                ('geo_long', models.CharField(max_length=16)),
                ('imgstate', models.CharField(max_length=16)),
                ('archive', models.CharField(max_length=8)),
                ('obs_type', models.CharField(max_length=8)),
                ('obs_id', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('raw', models.BooleanField()),
                ('cor', models.BooleanField()),
                ('cord', models.BooleanField()),
                ('clean', models.BooleanField()),
            ],
        ),
    ]
