# Generated by Django 6.0.5 on 2026-06-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitpix', models.IntegerField()),
                ('naxis', models.IntegerField()),
                ('naxis1', models.IntegerField()),
                ('naxis2', models.IntegerField()),
                ('extend', models.BooleanField()),
                ('bscale', models.FloatField()),
                ('bzero', models.IntegerField()),
                ('biassec', models.CharField(max_length=32)),
                ('trimsec', models.CharField(max_length=32)),
                ('datasec', models.CharField(max_length=32)),
                ('ccdsec', models.CharField(max_length=32)),
                ('gain', models.FloatField()),
                ('rdnoise', models.FloatField()),
                ('filter', models.CharField(max_length=32)),
                ('waveleng', models.IntegerField()),
                ('bandpass', models.CharField(max_length=32)),
                ('xbinning', models.IntegerField()),
                ('ybinning', models.IntegerField()),
                ('compr_al', models.CharField(max_length=32)),
                ('comp_set', models.CharField(max_length=16)),
                ('n_subimg', models.IntegerField()),
                ('overscan', models.IntegerField()),
                ('creator', models.CharField(max_length=16)),
                ('telescop', models.CharField(max_length=16)),
                ('shutter', models.CharField(max_length=16)),
                ('shut_age', models.FloatField()),
                ('detector', models.CharField(max_length=32)),
                ('timesys', models.CharField(max_length=4)),
                ('exposure', models.FloatField()),
                ('aexptime', models.FloatField()),
                ('rexptime', models.FloatField()),
                ('date_obs', models.DateTimeField()),
                ('time_obs', models.DateTimeField()),
                ('r_exp_s', models.DateTimeField()),
                ('a_exp_s', models.DateTimeField()),
                ('len_flu', models.FloatField()),
                ('len_tran', models.FloatField()),
                ('len_read', models.FloatField()),
                ('len_proc', models.FloatField()),
                ('lendelay', models.FloatField()),
                ('len_save', models.FloatField()),
                ('equinox', models.FloatField()),
                ('mode', models.CharField(max_length=32)),
                ('modetime', models.FloatField()),
                ('cmd', models.CharField(max_length=32)),
                ('cmdra', models.CharField(max_length=32)),
                ('cmddec', models.CharField(max_length=32)),
                ('cmdrol', models.FloatField()),
                ('cmdq0', models.FloatField()),
                ('cmdq1', models.FloatField()),
                ('cmdq2', models.FloatField()),
                ('cmdq3', models.FloatField()),
                ('ra', models.CharField(max_length=32)),
                ('dec', models.CharField(max_length=32)),
                ('objctra', models.CharField(max_length=32)),
                ('objctdec', models.CharField(max_length=32)),
                ('objctrol', models.FloatField()),
                ('ela_min', models.FloatField()),
                ('ela_max', models.FloatField()),
                ('ela_ang', models.FloatField()),
                ('sun_min', models.FloatField()),
                ('sun_max', models.FloatField()),
                ('hist_nb', models.IntegerField()),
                ('avg_vel', models.FloatField()),
                ('ra_vel', models.FloatField()),
                ('dev_vel', models.FloatField()),
                ('rol_vel', models.FloatField()),
                ('temp_ccd', models.FloatField()),
                ('ccdt_nb', models.IntegerField()),
                ('temp_roe', models.FloatField()),
                ('temp_amp', models.FloatField()),
                ('temp_pld', models.FloatField()),
                ('object', models.CharField(max_length=32)),
                ('observer', models.CharField(max_length=8)),
                ('intent', models.CharField(max_length=16)),
                ('instrume', models.CharField(max_length=16)),
                ('targtype', models.CharField(max_length=8)),
                ('prop_id', models.CharField(max_length=16)),
                ('pi_name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('moving', models.CharField(max_length=4)),
                ('m2', models.CharField(max_length=16)),
                ('geo_lat', models.CharField(max_length=16)),
                ('geo_long', models.CharField(max_length=16)),
                ('imgstate', models.CharField(max_length=16)),
                ('archive', models.CharField(max_length=8)),
                ('obs_type', models.CharField(max_length=8)),
                ('obs_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ObsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('s_path', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='date_obs',
            new_name='dt',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='aexptime',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmddec',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdq0',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdq1',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdq2',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdq3',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdra',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='cmdrol',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='day',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='ela_ang',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='ela_max',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='ela_min',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='geo_long',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='imgstate',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='instrume',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='moving',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='objctdec',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='objctra',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='objctrol',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='object',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='obs_id',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='obs_type',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='prop_id',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='rexptime',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='sun_max',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='sun_min',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='targtype',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='telescop',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='temp_ccd',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='time_obs',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='title',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='xbinning',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='ybinning',
        ),
        migrations.RemoveField(
            model_name='observationset',
            name='year',
        ),
        migrations.AddField(
            model_name='observationset',
            name='f_path',
            field=models.TextField(default='users/OpenData_DonneesOuvertes/pub/NEOSSAT/ASTRO/2026/109/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationset',
            name='name',
            field=models.TextField(default='NEOS_SCI_OLD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationset',
            name='saved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationset',
            name='raw_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizer.obsheader'),
        ),
        migrations.RunSQL("INSERT INTO visualizer_obslocation (id, domain, s_path) VALUES (0, 'data.asc-csa.gc.ca', 'users/OpenData_DonneesOuvertes/pub/NEOSSAT/ASTRO/2026/109/');"),
        migrations.AddField(
            model_name='observationset',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='visualizer.obslocation'),
            preserve_default=False,
        ),
    ]
