# Generated by Django 6.0.5 on 2026-06-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_obsheader_obslocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationset',
            old_name='raw_header',
            new_name='header',
        ),
    ]
