# Generated by Django 6.0.5 on 2026-06-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_rename_raw_header_observationset_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obsheader',
            old_name='dev_vel',
            new_name='dec_vel',
        ),
    ]
