# Generated by Django 6.0.5 on 2026-06-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_rename_dev_vel_obsheader_dec_vel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.obslocation'),
        ),
    ]
