# Generated by Django 6.0.5 on 2026-07-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0005_alter_observationset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationset',
            name='saved',
        ),
    ]
