# Generated by Django 6.0.5 on 2026-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0006_remove_observationset_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsheader',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
