services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/workspaces/astervis
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres-data: